config = {
    "keys_to_remove": [ 
      "lastModified",
      "thumbnailUrl",
      "role",
      "devStatus",
      "visible",
      "version",
      "editorType",
      "linkAccess",
      "prototypeStartNodeID",
      "flowStartingPoints",
      "layoutVersion",
      "lineTypes",
      "components",
      "componentSets",
      "schemaVersion",
      "lineIndentations",
      "overrides",
      "absoluteRenderBounds",
      "type",
      "componentId",
      "componentProperties",
      "styles",
      "id",
      "characterStyleOverrides",
      "arcData",
      "inheritFillStyleId",
      "inheritTextStyleId",
      "styleOverrideTable",
      "strokeAlign"
    ],
    "key_value_pairs_to_remove": [
      {"scrollBehavior":"SCROLLS"},
      {"blendMode": "NORMAL"},
      {"type": "SOLID"},
      {"constraints": {"vertical": "TOP", "horizontal": "LEFT"}},
      {"effects": []},
      {"background": []},
      {"fills": []},
      {"strokes": []},
      {"strokeWeight": 0},
      {"strokeAlign": "CENTER"},
      {"cornerRadius": 0},
      {"opacity": 1},
      {"rotation": 0},
      {"layoutGrids": []},
      {"layoutMode": "NONE"},
      {"primaryAxisSizingMode": "AUTO"},
      {"counterAxisSizingMode": "AUTO"},
      {"primaryAxisAlignItems": "MIN"},
      {"counterAxisAlignItems": "MIN"},
      {"layoutWrap": "NO_WRAP"},
      {"strokeWeight": 1},
      {"paddingLeft": 0},
      {"paddingRight": 0},
      {"paddingTop": 0},
      {"paddingBottom": 0},
      {"constraints": {
          "vertical": "SCALE",
          "horizontal": "SCALE"
      }},
      {"itemSpacing": 0},
      {"cornerSmoothing": 0},
      {"interactions": []},
      {"blendMode": "PASS_THROUGH"},
      {"type": "FRAME"},
      {"absoluteRenderBounds": None},
      {"absoluteBoundingBox": None},
      {"type": "TEXT"},
      {"showShadowBehindNode": False},
      {"strokeAlign": "INSIDE"},
      {"rectangleCornerRadii": [0.0,0.0,0.0,0.0]},
      {"strokeJoin": "ROUND"},
      {"strokeCap": "ROUND"},
      {"preserveRatio": True},
      {"lineHeightUnit": "FONT_SIZE_%"},
      {"characterStyleOverrides": []},
      {"styleOverrideTable": {}},
      {"clipsContent": False},
      {"type": "INSTANCE"},
      {"backgroundColor": {
        "r": 0.0,
        "g": 0.0,
        "b": 0.0,
        "a": 0.0
      }},
      {"letterSpacing": -0.0}
    ]
  }
  

  